### ISSUE TITLE
    groundingDINO error, output = _C.ms_deform_attn_forward( NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by suj99** [microsoft/TaskMatrix#368]
python visual_chatgpt.py --load "Text2Box_cuda:0,Segmenting_cuda:0,Inpainting_cuda:0,ImageCaptioning_cuda:0"

Got this error when tying the segment example, when using the segment or find prompt,
\anaconda3\envs\visgpt\lib\site-packages\groundingdino\models\GroundingDINO\ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined

I found a discussion about this issue at https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15. I was able to install GroundingDINO with GPU support by following the solutions provided there. Then, I copied the GroundingDINO folder to Anaconda3's visgpt environment, but I am still encountering the same error message.

I am running the script on a window laptop with gpu.

**Comment by suj99** [comment]
got answer from here
https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15

**Comment by SunTongtongtong** [comment]
@suj99 Can I know how do you solve it? 
I export CUDA_HOME and reinstall the groundDINO as seggested, but the problem exist.

**Comment by Famouzy** [comment]
If that help for someone:
I was downloaded the Nvidia Cuda version 11.8 and pip install Cython, then, i'm download and install GroundingDino, and problems are gone.
This site may help in providing GroundingDino for your version of cuda - https://pytorch.org/get-started/locally/
