### ISSUE TITLE
Where can I find visual-ChatGPT directory?

### ISSUE THREAD

**Issue by zhixun-luy** [microsoft/TaskMatrix#396]
![image](https://github.com/microsoft/TaskMatrix/assets/52573631/2ebb322a-6349-4f73-bdc4-12b5df737076)

**Comment by garychian** [comment]
same question here

**Comment by SantaKiller12** [comment]
It's just the TaskMatrix directory from the download.

**Comment by zhixun-luy** [comment]
Thank you for confirmation.
